# Teleop configuration for PS3 Navigation joystick.
teleop_twist_joy:
  axis_linear:
    x: 1
    y: 0
  scale_linear:
    x: 0.4
    y: 0.4
  axis_angular:
    yaw: 3
  scale_angular:
    yaw: 0.5
  enable_button: 10
  enable_turbo_button: 8
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
