footprint: [[-0.48, -0.4], [-0.48, 0.4], [0.48, 0.4], [0.48, -0.4]]
footprint_padding: 0.05

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5
raytrace_range: 5

#layer definitions
static:
  enable: true
  map_topic: /map
  subscribe_to_updates: true

obstacles_laser:
  enabled: true
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

inflation:
  enabled: true
  inflation_radius: 1.0
  cost_scaling_factor: 2.5
  is_raw_rosmessage: true
